export interface DrugInteraction {
  id: number;
  drug1: string;
  drug1Ar: string;
  drug2: string;
  drug2Ar: string;
  severity: "high" | "medium" | "low";
  category: string;
  categoryAr: string;
  descriptionEn: string;
  descriptionAr: string;
}

export interface InteractionCategory {
  id: string;
  name: string;
  nameAr: string;
}

export const interactionCategories: InteractionCategory[] = [
  { id: "heart", name: "Heart & Blood Pressure", nameAr: "القلب والضغط" },
  { id: "blood", name: "Blood Thinners", nameAr: "مسيلات الدم" },
  { id: "pain", name: "Pain & Anti-inflammatory", nameAr: "المسكنات ومضادات الالتهاب" },
  { id: "diabetes", name: "Diabetes", nameAr: "السكر" },
  { id: "antibiotics", name: "Antibiotics", nameAr: "المضادات الحيوية" },
  { id: "psychiatric", name: "Psychiatric & Neurological", nameAr: "الأدوية النفسية والعصبية" },
  { id: "stomach", name: "Stomach & Digestive", nameAr: "المعدة والجهاز الهضمي" },
  { id: "supplements", name: "Vitamins & Supplements", nameAr: "الفيتامينات والمكملات" },
  { id: "hormones", name: "Hormones", nameAr: "الهرمونات" },
  { id: "other", name: "Other", nameAr: "أخرى" },
];

export const drugInteractions: DrugInteraction[] = [
  // ===== HEART & BLOOD PRESSURE (1-10) =====
  {
    id: 1,
    drug1: "Amlodipine",
    drug1Ar: "أملوديبين",
    drug2: "Simvastatin",
    drug2Ar: "سيمفاستاتين",
    severity: "high",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Amlodipine increases simvastatin blood levels, raising the risk of rhabdomyolysis (muscle breakdown). Simvastatin dose should not exceed 20 mg daily when combined.",
    descriptionAr: "أملوديبين يزيد مستوى سيمفاستاتين في الدم مما يرفع خطر انحلال العضلات. يجب ألا تتجاوز جرعة سيمفاستاتين 20 مجم يومياً عند الجمع بينهما.",
  },
  {
    id: 2,
    drug1: "Atenolol",
    drug1Ar: "أتينولول",
    drug2: "Verapamil",
    drug2Ar: "فيراباميل",
    severity: "high",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Both drugs slow heart rate and conduction. Combined use can cause severe bradycardia, heart block, or cardiac arrest.",
    descriptionAr: "كلا الدواءين يبطئ معدل ضربات القلب والتوصيل الكهربائي. الجمع بينهما قد يسبب بطء شديد في القلب أو توقف القلب.",
  },
  {
    id: 3,
    drug1: "Lisinopril",
    drug1Ar: "ليسينوبريل",
    drug2: "Spironolactone",
    drug2Ar: "سبيرونولاكتون",
    severity: "high",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Both increase potassium levels. Combined use significantly raises the risk of life-threatening hyperkalemia.",
    descriptionAr: "كلاهما يرفع مستوى البوتاسيوم. الجمع بينهما يزيد بشكل كبير خطر ارتفاع البوتاسيوم المهدد للحياة.",
  },
  {
    id: 4,
    drug1: "Digoxin",
    drug1Ar: "ديجوكسين",
    drug2: "Amiodarone",
    drug2Ar: "أميودارون",
    severity: "high",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Amiodarone increases digoxin levels by up to 70%, risking digoxin toxicity with symptoms like nausea, vision changes, and arrhythmias.",
    descriptionAr: "أميودارون يزيد مستوى الديجوكسين حتى 70%، مما يعرض لخطر تسمم الديجوكسين مع أعراض كالغثيان وتغيرات الرؤية واضطراب النظم.",
  },
  {
    id: 5,
    drug1: "Enalapril",
    drug1Ar: "إنالابريل",
    drug2: "Losartan",
    drug2Ar: "لوسارتان",
    severity: "high",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Dual blockade of the renin-angiotensin system increases the risk of hypotension, hyperkalemia, and renal impairment without added benefit.",
    descriptionAr: "الحصار المزدوج لنظام الرينين-أنجيوتنسين يزيد خطر انخفاض الضغط وارتفاع البوتاسيوم والقصور الكلوي دون فائدة إضافية.",
  },
  {
    id: 6,
    drug1: "Bisoprolol",
    drug1Ar: "بيسوبرولول",
    drug2: "Clonidine",
    drug2Ar: "كلونيدين",
    severity: "medium",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Stopping clonidine while on a beta-blocker can cause rebound hypertensive crisis. If discontinuation is needed, taper clonidine first.",
    descriptionAr: "إيقاف كلونيدين أثناء تناول حاصرات بيتا قد يسبب ارتفاع ضغط ارتدادي حاد. يجب تقليل كلونيدين تدريجياً أولاً.",
  },
  {
    id: 7,
    drug1: "Nifedipine",
    drug1Ar: "نيفيديبين",
    drug2: "Propranolol",
    drug2Ar: "بروبرانولول",
    severity: "medium",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Combined use can cause excessive hypotension and possible heart failure, especially in patients with compromised cardiac function.",
    descriptionAr: "الجمع بينهما قد يسبب انخفاضاً مفرطاً في الضغط وفشلاً في القلب، خاصة في المرضى ذوي وظائف القلب الضعيفة.",
  },
  {
    id: 8,
    drug1: "Furosemide",
    drug1Ar: "فيوروسيميد",
    drug2: "Gentamicin",
    drug2Ar: "جنتاميسين",
    severity: "high",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Both are ototoxic and nephrotoxic. Combined use significantly increases the risk of permanent hearing loss and kidney damage.",
    descriptionAr: "كلاهما سام للأذن والكلى. الجمع بينهما يزيد بشكل كبير خطر فقدان السمع الدائم وتلف الكلى.",
  },
  {
    id: 9,
    drug1: "Diltiazem",
    drug1Ar: "ديلتيازيم",
    drug2: "Atorvastatin",
    drug2Ar: "أتورفاستاتين",
    severity: "medium",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Diltiazem inhibits CYP3A4 and increases statin levels, raising the risk of myopathy. Monitor for muscle pain and weakness.",
    descriptionAr: "ديلتيازيم يثبط إنزيم CYP3A4 ويزيد مستوى الستاتين، مما يرفع خطر اعتلال العضلات. يجب مراقبة آلام وضعف العضلات.",
  },
  {
    id: 10,
    drug1: "Hydrochlorothiazide",
    drug1Ar: "هيدروكلوروثيازيد",
    drug2: "Lithium",
    drug2Ar: "ليثيوم",
    severity: "high",
    category: "heart",
    categoryAr: "القلب والضغط",
    descriptionEn: "Thiazide diuretics reduce lithium clearance, causing dangerous lithium accumulation and toxicity.",
    descriptionAr: "مدرات الثيازيد تقلل تصفية الليثيوم مما يسبب تراكمه بشكل خطير وحدوث تسمم.",
  },

  // ===== BLOOD THINNERS (11-20) =====
  {
    id: 11,
    drug1: "Warfarin",
    drug1Ar: "وارفارين",
    drug2: "Aspirin",
    drug2Ar: "أسبرين",
    severity: "high",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Both impair hemostasis through different mechanisms. Combined use significantly increases the risk of gastrointestinal and intracranial bleeding.",
    descriptionAr: "كلاهما يضعف تخثر الدم بآليات مختلفة. الجمع بينهما يزيد بشكل كبير خطر النزيف المعدي المعوي والدماغي.",
  },
  {
    id: 12,
    drug1: "Warfarin",
    drug1Ar: "وارفارين",
    drug2: "Ibuprofen",
    drug2Ar: "بروفين",
    severity: "high",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Ibuprofen inhibits platelets and irritates the gastric mucosa, greatly increasing bleeding risk in warfarin patients.",
    descriptionAr: "بروفين يثبط الصفائح الدموية ويهيج الغشاء المخاطي للمعدة، مما يزيد خطر النزيف بشكل كبير مع وارفارين.",
  },
  {
    id: 13,
    drug1: "Warfarin",
    drug1Ar: "وارفارين",
    drug2: "Metronidazole",
    drug2Ar: "ميترونيدازول",
    severity: "high",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Metronidazole inhibits warfarin metabolism, significantly increasing INR and risk of major bleeding.",
    descriptionAr: "ميترونيدازول يثبط أيض وارفارين مما يزيد بشكل كبير قيمة INR وخطر النزيف الحاد.",
  },
  {
    id: 14,
    drug1: "Clopidogrel",
    drug1Ar: "كلوبيدوجريل",
    drug2: "Omeprazole",
    drug2Ar: "أوميبرازول",
    severity: "medium",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Omeprazole inhibits CYP2C19, reducing conversion of clopidogrel to its active form and decreasing its antiplatelet effect.",
    descriptionAr: "أوميبرازول يثبط إنزيم CYP2C19 مما يقلل تحويل كلوبيدوجريل لصورته الفعالة ويضعف تأثيره المضاد للصفائح.",
  },
  {
    id: 15,
    drug1: "Warfarin",
    drug1Ar: "وارفارين",
    drug2: "Amoxicillin",
    drug2Ar: "أموكسيسيللين",
    severity: "medium",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Amoxicillin may reduce vitamin K-producing gut bacteria, enhancing warfarin's anticoagulant effect and raising bleeding risk.",
    descriptionAr: "أموكسيسيللين قد يقلل بكتيريا الأمعاء المنتجة لفيتامين ك مما يعزز تأثير وارفارين ويزيد خطر النزيف.",
  },
  {
    id: 16,
    drug1: "Rivaroxaban",
    drug1Ar: "ريفاروكسابان",
    drug2: "Ketoconazole",
    drug2Ar: "كيتوكونازول",
    severity: "high",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Ketoconazole strongly inhibits CYP3A4 and P-glycoprotein, dramatically increasing rivaroxaban levels and bleeding risk.",
    descriptionAr: "كيتوكونازول يثبط بقوة CYP3A4 والبروتين السكري-P مما يزيد مستوى ريفاروكسابان بشكل كبير وخطر النزيف.",
  },
  {
    id: 17,
    drug1: "Aspirin",
    drug1Ar: "أسبرين",
    drug2: "Clopidogrel",
    drug2Ar: "كلوبيدوجريل",
    severity: "medium",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Dual antiplatelet therapy increases bleeding risk, especially GI bleeding. Often used intentionally post-stent but requires monitoring.",
    descriptionAr: "العلاج المزدوج المضاد للصفائح يزيد خطر النزيف خاصة المعدي المعوي. يستخدم عادة بعد تركيب الدعامة ولكن يتطلب متابعة.",
  },
  {
    id: 18,
    drug1: "Warfarin",
    drug1Ar: "وارفارين",
    drug2: "Fluconazole",
    drug2Ar: "فلوكونازول",
    severity: "high",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Fluconazole inhibits CYP2C9 and CYP3A4, significantly increasing warfarin levels and risk of life-threatening bleeding.",
    descriptionAr: "فلوكونازول يثبط إنزيمات CYP2C9 وCYP3A4 مما يزيد بشكل كبير مستوى وارفارين وخطر النزيف المهدد للحياة.",
  },
  {
    id: 19,
    drug1: "Heparin",
    drug1Ar: "هيبارين",
    drug2: "Aspirin",
    drug2Ar: "أسبرين",
    severity: "high",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Combined anticoagulant and antiplatelet effects greatly increase the risk of hemorrhage, including intracranial bleeding.",
    descriptionAr: "التأثير المشترك لمضاد التخثر ومضاد الصفائح يزيد بشكل كبير خطر النزيف بما في ذلك النزيف داخل الجمجمة.",
  },
  {
    id: 20,
    drug1: "Warfarin",
    drug1Ar: "وارفارين",
    drug2: "Rifampicin",
    drug2Ar: "ريفامبيسين",
    severity: "high",
    category: "blood",
    categoryAr: "مسيلات الدم",
    descriptionEn: "Rifampicin is a potent CYP enzyme inducer that dramatically reduces warfarin levels, potentially causing treatment failure and thrombosis.",
    descriptionAr: "ريفامبيسين محفز قوي لإنزيمات CYP يقلل بشكل كبير مستوى وارفارين مما قد يسبب فشل العلاج وحدوث جلطات.",
  },

  // ===== PAIN & ANTI-INFLAMMATORY (21-30) =====
  {
    id: 21,
    drug1: "Ibuprofen",
    drug1Ar: "بروفين",
    drug2: "Aspirin",
    drug2Ar: "أسبرين",
    severity: "medium",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "Ibuprofen can block aspirin's antiplatelet binding site, reducing its cardioprotective effect. Take aspirin at least 30 minutes before ibuprofen.",
    descriptionAr: "بروفين قد يمنع ارتباط الأسبرين بالصفائح الدموية مما يقلل تأثيره الوقائي للقلب. يجب تناول الأسبرين قبل بروفين بـ30 دقيقة على الأقل.",
  },
  {
    id: 22,
    drug1: "Diclofenac",
    drug1Ar: "ديكلوفيناك",
    drug2: "Lisinopril",
    drug2Ar: "ليسينوبريل",
    severity: "medium",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "NSAIDs reduce the antihypertensive effect of ACE inhibitors and increase the risk of acute kidney injury, especially in dehydrated patients.",
    descriptionAr: "مضادات الالتهاب غير الستيرويدية تقلل تأثير مثبطات ACE الخافضة للضغط وتزيد خطر القصور الكلوي الحاد خاصة في حالات الجفاف.",
  },
  {
    id: 23,
    drug1: "Paracetamol",
    drug1Ar: "باراسيتامول",
    drug2: "Warfarin",
    drug2Ar: "وارفارين",
    severity: "medium",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "Regular paracetamol use (>2g/day for several days) can increase INR in warfarin patients. Occasional use is generally safe.",
    descriptionAr: "الاستخدام المنتظم للباراسيتامول (أكثر من 2 جم يومياً لعدة أيام) قد يزيد INR في مرضى وارفارين. الاستخدام العرضي آمن عموماً.",
  },
  {
    id: 24,
    drug1: "Tramadol",
    drug1Ar: "ترامادول",
    drug2: "Sertraline",
    drug2Ar: "سيرترالين",
    severity: "high",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "Both increase serotonin levels. Combined use can cause serotonin syndrome with symptoms like agitation, tremor, hyperthermia, and seizures.",
    descriptionAr: "كلاهما يزيد مستوى السيروتونين. الجمع بينهما قد يسبب متلازمة السيروتونين مع أعراض كالهياج والرعشة وارتفاع الحرارة والتشنجات.",
  },
  {
    id: 25,
    drug1: "Ibuprofen",
    drug1Ar: "بروفين",
    drug2: "Methotrexate",
    drug2Ar: "ميثوتريكسات",
    severity: "high",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "NSAIDs reduce renal clearance of methotrexate, leading to dangerously elevated levels and risk of severe bone marrow suppression.",
    descriptionAr: "مضادات الالتهاب غير الستيرويدية تقلل التصفية الكلوية للميثوتريكسات مما يؤدي لارتفاع خطير في مستوياته وخطر تثبيط نخاع العظم.",
  },
  {
    id: 26,
    drug1: "Diclofenac",
    drug1Ar: "ديكلوفيناك",
    drug2: "Furosemide",
    drug2Ar: "فيوروسيميد",
    severity: "medium",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "NSAIDs reduce the diuretic and antihypertensive effects of furosemide and can increase the risk of nephrotoxicity.",
    descriptionAr: "مضادات الالتهاب غير الستيرويدية تقلل التأثير المدر للبول والخافض للضغط لفيوروسيميد وقد تزيد خطر السمية الكلوية.",
  },
  {
    id: 27,
    drug1: "Celecoxib",
    drug1Ar: "سيليكوكسيب",
    drug2: "Fluconazole",
    drug2Ar: "فلوكونازول",
    severity: "medium",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "Fluconazole inhibits CYP2C9, increasing celecoxib plasma levels and the risk of cardiovascular and gastrointestinal side effects.",
    descriptionAr: "فلوكونازول يثبط إنزيم CYP2C9 مما يزيد مستوى سيليكوكسيب في الدم وخطر الآثار الجانبية القلبية والمعدية المعوية.",
  },
  {
    id: 28,
    drug1: "Codeine",
    drug1Ar: "كودايين",
    drug2: "Diazepam",
    drug2Ar: "ديازيبام",
    severity: "high",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "Combined CNS depressant effects can cause severe respiratory depression, profound sedation, coma, and death.",
    descriptionAr: "التأثير المشترك المثبط للجهاز العصبي المركزي قد يسبب تثبيطاً تنفسياً شديداً وتخديراً عميقاً وغيبوبة ووفاة.",
  },
  {
    id: 29,
    drug1: "Naproxen",
    drug1Ar: "نابروكسين",
    drug2: "Prednisolone",
    drug2Ar: "بريدنيزولون",
    severity: "medium",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "Both increase the risk of gastrointestinal ulceration and bleeding. Combined use requires gastroprotection with a proton pump inhibitor.",
    descriptionAr: "كلاهما يزيد خطر تقرح ونزيف الجهاز الهضمي. الجمع بينهما يتطلب حماية المعدة بمثبط مضخة البروتون.",
  },
  {
    id: 30,
    drug1: "Ketoprofen",
    drug1Ar: "كيتوبروفين",
    drug2: "Lithium",
    drug2Ar: "ليثيوم",
    severity: "high",
    category: "pain",
    categoryAr: "المسكنات ومضادات الالتهاب",
    descriptionEn: "NSAIDs reduce renal lithium clearance, causing lithium accumulation and potential toxicity with tremor, confusion, and seizures.",
    descriptionAr: "مضادات الالتهاب غير الستيرويدية تقلل التصفية الكلوية لليثيوم مما يسبب تراكمه وخطر التسمم مع رعشة وارتباك وتشنجات.",
  },

  // ===== DIABETES (31-40) =====
  {
    id: 31,
    drug1: "Metformin",
    drug1Ar: "ميتفورمين",
    drug2: "Contrast Dye (Iodinated)",
    drug2Ar: "صبغة الأشعة (اليود)",
    severity: "high",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Iodinated contrast media can cause acute kidney injury, leading to metformin accumulation and life-threatening lactic acidosis.",
    descriptionAr: "صبغة الأشعة اليودية قد تسبب قصوراً كلوياً حاداً مما يؤدي لتراكم ميتفورمين وحماض لاكتيكي مهدد للحياة.",
  },
  {
    id: 32,
    drug1: "Glimepiride",
    drug1Ar: "جليميبيريد",
    drug2: "Fluconazole",
    drug2Ar: "فلوكونازول",
    severity: "high",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Fluconazole inhibits CYP2C9, increasing glimepiride levels and causing prolonged severe hypoglycemia.",
    descriptionAr: "فلوكونازول يثبط إنزيم CYP2C9 مما يزيد مستوى جليميبيريد ويسبب انخفاضاً حاداً ومطولاً في سكر الدم.",
  },
  {
    id: 33,
    drug1: "Insulin",
    drug1Ar: "إنسولين",
    drug2: "Propranolol",
    drug2Ar: "بروبرانولول",
    severity: "medium",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Beta-blockers mask hypoglycemia warning symptoms (tremor, palpitations) and may prolong hypoglycemic episodes.",
    descriptionAr: "حاصرات بيتا تخفي أعراض انخفاض السكر التحذيرية (الرعشة وخفقان القلب) وقد تطيل نوبات انخفاض السكر.",
  },
  {
    id: 34,
    drug1: "Metformin",
    drug1Ar: "ميتفورمين",
    drug2: "Alcohol",
    drug2Ar: "كحول",
    severity: "high",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Alcohol increases the risk of metformin-associated lactic acidosis, especially in patients with liver disease or during binge drinking.",
    descriptionAr: "الكحول يزيد خطر الحماض اللاكتيكي المرتبط بميتفورمين خاصة في مرضى الكبد أو عند الإفراط في الشرب.",
  },
  {
    id: 35,
    drug1: "Gliclazide",
    drug1Ar: "جليكلازيد",
    drug2: "Ciprofloxacin",
    drug2Ar: "سيبروفلوكساسين",
    severity: "medium",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Ciprofloxacin can increase insulin secretion and enhance sulfonylurea effects, leading to hypoglycemia.",
    descriptionAr: "سيبروفلوكساسين قد يزيد إفراز الإنسولين ويعزز تأثير السلفونيل يوريا مما يؤدي لانخفاض سكر الدم.",
  },
  {
    id: 36,
    drug1: "Pioglitazone",
    drug1Ar: "بيوجليتازون",
    drug2: "Insulin",
    drug2Ar: "إنسولين",
    severity: "medium",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Combined use increases the risk of fluid retention, weight gain, and heart failure, especially in susceptible patients.",
    descriptionAr: "الجمع بينهما يزيد خطر احتباس السوائل وزيادة الوزن وفشل القلب خاصة في المرضى المعرضين.",
  },
  {
    id: 37,
    drug1: "Glibenclamide",
    drug1Ar: "جليبنكلاميد",
    drug2: "Prednisolone",
    drug2Ar: "بريدنيزولون",
    severity: "medium",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Corticosteroids raise blood glucose levels, counteracting the hypoglycemic effect of sulfonylureas. Dose adjustment is often needed.",
    descriptionAr: "الكورتيكوستيرويدات ترفع مستوى سكر الدم مما يعاكس تأثير السلفونيل يوريا الخافض للسكر. غالباً يحتاج تعديل الجرعة.",
  },
  {
    id: 38,
    drug1: "Empagliflozin",
    drug1Ar: "إمباجليفلوزين",
    drug2: "Furosemide",
    drug2Ar: "فيوروسيميد",
    severity: "medium",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Both cause diuresis and volume depletion. Combined use increases the risk of dehydration, hypotension, and acute kidney injury.",
    descriptionAr: "كلاهما يسبب إدراراً للبول ونقصاً في حجم السوائل. الجمع بينهما يزيد خطر الجفاف وانخفاض الضغط والقصور الكلوي.",
  },
  {
    id: 39,
    drug1: "Sitagliptin",
    drug1Ar: "سيتاجليبتين",
    drug2: "Glimepiride",
    drug2Ar: "جليميبيريد",
    severity: "low",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Adding a DPP-4 inhibitor to a sulfonylurea increases hypoglycemia risk. Sulfonylurea dose reduction may be required.",
    descriptionAr: "إضافة مثبط DPP-4 إلى السلفونيل يوريا يزيد خطر انخفاض السكر. قد يلزم تقليل جرعة السلفونيل يوريا.",
  },
  {
    id: 40,
    drug1: "Metformin",
    drug1Ar: "ميتفورمين",
    drug2: "Dapagliflozin",
    drug2Ar: "داباجليفلوزين",
    severity: "low",
    category: "diabetes",
    categoryAr: "السكر",
    descriptionEn: "Generally a safe combination, but both can affect renal function. Monitor kidney function and watch for urinary tract infections.",
    descriptionAr: "الجمع بينهما آمن عموماً لكن كلاهما قد يؤثر على وظائف الكلى. يجب مراقبة وظائف الكلى والانتباه لعدوى المسالك البولية.",
  },

  // ===== ANTIBIOTICS (41-50) =====
  {
    id: 41,
    drug1: "Ciprofloxacin",
    drug1Ar: "سيبروفلوكساسين",
    drug2: "Theophylline",
    drug2Ar: "ثيوفيللين",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Ciprofloxacin inhibits theophylline metabolism, causing toxic levels with seizures, arrhythmias, and potential death.",
    descriptionAr: "سيبروفلوكساسين يثبط أيض ثيوفيللين مما يسبب مستويات سامة مع تشنجات واضطرابات نظم قد تكون مميتة.",
  },
  {
    id: 42,
    drug1: "Erythromycin",
    drug1Ar: "إريثروميسين",
    drug2: "Simvastatin",
    drug2Ar: "سيمفاستاتين",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Erythromycin inhibits CYP3A4, markedly increasing statin levels and the risk of fatal rhabdomyolysis.",
    descriptionAr: "إريثروميسين يثبط إنزيم CYP3A4 مما يزيد بشكل ملحوظ مستوى الستاتين وخطر انحلال العضلات المميت.",
  },
  {
    id: 43,
    drug1: "Azithromycin",
    drug1Ar: "أزيثروميسين",
    drug2: "Amiodarone",
    drug2Ar: "أميودارون",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Both prolong the QT interval. Combined use significantly increases the risk of torsades de pointes, a life-threatening arrhythmia.",
    descriptionAr: "كلاهما يطيل فترة QT. الجمع بينهما يزيد بشكل كبير خطر اضطراب نظم القلب (تورساد دي بوانت) المهدد للحياة.",
  },
  {
    id: 44,
    drug1: "Tetracycline",
    drug1Ar: "تتراسيكلين",
    drug2: "Antacids (Calcium/Aluminum)",
    drug2Ar: "مضادات الحموضة (كالسيوم/ألومنيوم)",
    severity: "medium",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Metal cations in antacids chelate tetracycline, dramatically reducing its absorption and antibiotic efficacy.",
    descriptionAr: "الأيونات المعدنية في مضادات الحموضة ترتبط بالتتراسيكلين مما يقلل بشكل كبير امتصاصه وفعاليته كمضاد حيوي.",
  },
  {
    id: 45,
    drug1: "Ciprofloxacin",
    drug1Ar: "سيبروفلوكساسين",
    drug2: "Iron Supplements",
    drug2Ar: "مكملات الحديد",
    severity: "medium",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Iron chelates ciprofloxacin in the GI tract, reducing antibiotic absorption by up to 50%. Separate doses by at least 2 hours.",
    descriptionAr: "الحديد يرتبط بالسيبروفلوكساسين في الجهاز الهضمي مما يقلل امتصاص المضاد الحيوي حتى 50%. يجب الفصل بساعتين على الأقل.",
  },
  {
    id: 46,
    drug1: "Trimethoprim-Sulfamethoxazole",
    drug1Ar: "تريميثوبريم-سلفاميثوكسازول",
    drug2: "Enalapril",
    drug2Ar: "إنالابريل",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Trimethoprim acts like a potassium-sparing diuretic. Combined with ACE inhibitors, it significantly increases the risk of fatal hyperkalemia.",
    descriptionAr: "تريميثوبريم يعمل كمدر بول حافظ للبوتاسيوم. مع مثبطات ACE يزيد بشكل كبير خطر ارتفاع البوتاسيوم المميت.",
  },
  {
    id: 47,
    drug1: "Clarithromycin",
    drug1Ar: "كلاريثروميسين",
    drug2: "Colchicine",
    drug2Ar: "كولشيسين",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Clarithromycin inhibits CYP3A4 and P-glycoprotein, dramatically increasing colchicine levels. Fatal toxicity has been reported.",
    descriptionAr: "كلاريثروميسين يثبط CYP3A4 والبروتين السكري-P مما يزيد مستوى كولشيسين بشكل كبير. تم تسجيل حالات تسمم مميتة.",
  },
  {
    id: 48,
    drug1: "Rifampicin",
    drug1Ar: "ريفامبيسين",
    drug2: "Oral Contraceptives",
    drug2Ar: "حبوب منع الحمل",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Rifampicin induces CYP3A4, drastically reducing contraceptive hormone levels and causing contraceptive failure.",
    descriptionAr: "ريفامبيسين يحفز إنزيم CYP3A4 مما يقلل بشكل كبير مستوى هرمونات منع الحمل ويسبب فشل وسيلة منع الحمل.",
  },
  {
    id: 49,
    drug1: "Doxycycline",
    drug1Ar: "دوكسيسيكلين",
    drug2: "Isotretinoin",
    drug2Ar: "أيزوتريتينوين",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Both can increase intracranial pressure. Combined use raises the risk of pseudotumor cerebri with headache, vision loss, and papilledema.",
    descriptionAr: "كلاهما قد يزيد الضغط داخل الجمجمة. الجمع بينهما يزيد خطر الورم الكاذب المخي مع صداع وفقدان بصر ووذمة حليمة العصب.",
  },
  {
    id: 50,
    drug1: "Metronidazole",
    drug1Ar: "ميترونيدازول",
    drug2: "Alcohol",
    drug2Ar: "كحول",
    severity: "high",
    category: "antibiotics",
    categoryAr: "المضادات الحيوية",
    descriptionEn: "Metronidazole causes a disulfiram-like reaction with alcohol, leading to severe nausea, vomiting, flushing, and tachycardia.",
    descriptionAr: "ميترونيدازول يسبب تفاعلاً شبيهاً بالديسلفرام مع الكحول مما يؤدي لغثيان شديد وقيء واحمرار وتسارع في القلب.",
  },

  // ===== PSYCHIATRIC & NEUROLOGICAL (51-60) =====
  {
    id: 51,
    drug1: "Fluoxetine",
    drug1Ar: "فلوكسيتين",
    drug2: "Tramadol",
    drug2Ar: "ترامادول",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Both increase serotonin. Combined use risks serotonin syndrome and fluoxetine also inhibits tramadol activation via CYP2D6.",
    descriptionAr: "كلاهما يزيد السيروتونين. الجمع بينهما يخاطر بمتلازمة السيروتونين وفلوكسيتين يثبط أيضاً تنشيط ترامادول عبر CYP2D6.",
  },
  {
    id: 52,
    drug1: "Carbamazepine",
    drug1Ar: "كاربامازيبين",
    drug2: "Erythromycin",
    drug2Ar: "إريثروميسين",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Erythromycin inhibits carbamazepine metabolism, causing toxic levels with dizziness, ataxia, drowsiness, and diplopia.",
    descriptionAr: "إريثروميسين يثبط أيض كاربامازيبين مما يسبب مستويات سامة مع دوخة وترنح ونعاس وازدواج الرؤية.",
  },
  {
    id: 53,
    drug1: "Sertraline",
    drug1Ar: "سيرترالين",
    drug2: "MAO Inhibitors",
    drug2Ar: "مثبطات MAO",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Absolute contraindication. Combined use can cause fatal serotonin syndrome. A 14-day washout period is required between them.",
    descriptionAr: "ممنوع الجمع بينهما تماماً. قد يسبب متلازمة سيروتونين مميتة. يجب فترة انتظار 14 يوماً بينهما.",
  },
  {
    id: 54,
    drug1: "Phenytoin",
    drug1Ar: "فينيتوين",
    drug2: "Valproic Acid",
    drug2Ar: "حمض الفالبرويك",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Complex interaction: valproic acid displaces phenytoin from protein binding and inhibits its metabolism, increasing free phenytoin toxicity.",
    descriptionAr: "تفاعل معقد: حمض الفالبرويك يزيح الفينيتوين من ارتباطه بالبروتين ويثبط أيضه مما يزيد سمية الفينيتوين الحر.",
  },
  {
    id: 55,
    drug1: "Alprazolam",
    drug1Ar: "ألبرازولام",
    drug2: "Alcohol",
    drug2Ar: "كحول",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Synergistic CNS depression can cause fatal respiratory depression. This is one of the most common causes of overdose death.",
    descriptionAr: "التثبيط التآزري للجهاز العصبي المركزي قد يسبب تثبيطاً تنفسياً مميتاً. هذا من أكثر أسباب الوفاة بالجرعة الزائدة شيوعاً.",
  },
  {
    id: 56,
    drug1: "Paroxetine",
    drug1Ar: "باروكسيتين",
    drug2: "Tamoxifen",
    drug2Ar: "تاموكسيفين",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Paroxetine strongly inhibits CYP2D6, preventing conversion of tamoxifen to its active metabolite and reducing its anticancer efficacy.",
    descriptionAr: "باروكسيتين يثبط بقوة إنزيم CYP2D6 مما يمنع تحويل تاموكسيفين لمادته الفعالة ويقلل فعاليته ضد السرطان.",
  },
  {
    id: 57,
    drug1: "Amitriptyline",
    drug1Ar: "أميتريبتيلين",
    drug2: "Clonidine",
    drug2Ar: "كلونيدين",
    severity: "medium",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Tricyclic antidepressants can block the antihypertensive effect of clonidine, leading to dangerous blood pressure elevation.",
    descriptionAr: "مضادات الاكتئاب ثلاثية الحلقات قد تمنع التأثير الخافض للضغط لكلونيدين مما يؤدي لارتفاع خطير في ضغط الدم.",
  },
  {
    id: 58,
    drug1: "Haloperidol",
    drug1Ar: "هالوبيريدول",
    drug2: "Metoclopramide",
    drug2Ar: "ميتوكلوبراميد",
    severity: "medium",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Both block dopamine receptors. Combined use increases the risk of extrapyramidal symptoms and neuroleptic malignant syndrome.",
    descriptionAr: "كلاهما يحجب مستقبلات الدوبامين. الجمع بينهما يزيد خطر الأعراض خارج الهرمية ومتلازمة الذهان الخبيثة.",
  },
  {
    id: 59,
    drug1: "Levodopa",
    drug1Ar: "ليفودوبا",
    drug2: "Haloperidol",
    drug2Ar: "هالوبيريدول",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Haloperidol blocks dopamine receptors, directly antagonizing levodopa's therapeutic effect in Parkinson's disease.",
    descriptionAr: "هالوبيريدول يحجب مستقبلات الدوبامين مما يعاكس مباشرة التأثير العلاجي لليفودوبا في مرض باركنسون.",
  },
  {
    id: 60,
    drug1: "Gabapentin",
    drug1Ar: "جابابنتين",
    drug2: "Morphine",
    drug2Ar: "مورفين",
    severity: "high",
    category: "psychiatric",
    categoryAr: "الأدوية النفسية والعصبية",
    descriptionEn: "Morphine increases gabapentin absorption. Combined CNS depression increases the risk of respiratory depression and death.",
    descriptionAr: "المورفين يزيد امتصاص جابابنتين. التثبيط المشترك للجهاز العصبي المركزي يزيد خطر التثبيط التنفسي والوفاة.",
  },

  // ===== STOMACH & DIGESTIVE (61-70) =====
  {
    id: 61,
    drug1: "Omeprazole",
    drug1Ar: "أوميبرازول",
    drug2: "Clopidogrel",
    drug2Ar: "كلوبيدوجريل",
    severity: "medium",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "Omeprazole inhibits CYP2C19, reducing clopidogrel activation. Consider pantoprazole as a safer alternative PPI.",
    descriptionAr: "أوميبرازول يثبط إنزيم CYP2C19 مما يقلل تنشيط كلوبيدوجريل. يفضل استخدام بانتوبرازول كبديل أكثر أماناً.",
  },
  {
    id: 62,
    drug1: "Omeprazole",
    drug1Ar: "أوميبرازول",
    drug2: "Methotrexate",
    drug2Ar: "ميثوتريكسات",
    severity: "medium",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "PPIs can decrease methotrexate renal clearance, increasing its levels and risk of toxicity, especially at high doses.",
    descriptionAr: "مثبطات مضخة البروتون قد تقلل التصفية الكلوية للميثوتريكسات مما يزيد مستوياته وخطر التسمم خاصة بالجرعات العالية.",
  },
  {
    id: 63,
    drug1: "Ranitidine",
    drug1Ar: "رانيتيدين",
    drug2: "Ketoconazole",
    drug2Ar: "كيتوكونازول",
    severity: "medium",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "H2 blockers raise gastric pH, significantly reducing ketoconazole absorption which requires an acidic environment.",
    descriptionAr: "حاصرات H2 ترفع حموضة المعدة مما يقلل بشكل كبير امتصاص كيتوكونازول الذي يحتاج بيئة حمضية.",
  },
  {
    id: 64,
    drug1: "Antacids (Aluminum/Magnesium)",
    drug1Ar: "مضادات الحموضة (ألومنيوم/ماغنسيوم)",
    drug2: "Levothyroxine",
    drug2Ar: "ليفوثيروكسين",
    severity: "medium",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "Antacids bind levothyroxine in the gut, significantly reducing its absorption. Separate doses by at least 4 hours.",
    descriptionAr: "مضادات الحموضة ترتبط بالليفوثيروكسين في الأمعاء مما يقلل امتصاصه بشكل كبير. يجب الفصل بـ4 ساعات على الأقل.",
  },
  {
    id: 65,
    drug1: "Domperidone",
    drug1Ar: "دومبيريدون",
    drug2: "Erythromycin",
    drug2Ar: "إريثروميسين",
    severity: "high",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "Both prolong the QT interval. Combined use increases the risk of fatal cardiac arrhythmias, especially torsades de pointes.",
    descriptionAr: "كلاهما يطيل فترة QT. الجمع بينهما يزيد خطر اضطرابات نظم القلب المميتة خاصة تورساد دي بوانت.",
  },
  {
    id: 66,
    drug1: "Sucralfate",
    drug1Ar: "سوكرالفيت",
    drug2: "Ciprofloxacin",
    drug2Ar: "سيبروفلوكساسين",
    severity: "medium",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "Sucralfate contains aluminum which chelates ciprofloxacin, reducing its absorption by up to 90%. Separate by at least 2 hours.",
    descriptionAr: "سوكرالفيت يحتوي على الألومنيوم الذي يرتبط بالسيبروفلوكساسين ويقلل امتصاصه حتى 90%. يجب الفصل بساعتين على الأقل.",
  },
  {
    id: 67,
    drug1: "Metoclopramide",
    drug1Ar: "ميتوكلوبراميد",
    drug2: "Levodopa",
    drug2Ar: "ليفودوبا",
    severity: "high",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "Metoclopramide blocks central dopamine receptors, antagonizing levodopa's effect and worsening Parkinson's symptoms.",
    descriptionAr: "ميتوكلوبراميد يحجب مستقبلات الدوبامين المركزية مما يعاكس تأثير ليفودوبا ويزيد أعراض باركنسون سوءاً.",
  },
  {
    id: 68,
    drug1: "Esomeprazole",
    drug1Ar: "إيزوميبرازول",
    drug2: "Iron Supplements",
    drug2Ar: "مكملات الحديد",
    severity: "low",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "PPIs reduce gastric acid needed for iron absorption. Long-term PPI use may contribute to iron deficiency.",
    descriptionAr: "مثبطات مضخة البروتون تقلل حمض المعدة اللازم لامتصاص الحديد. الاستخدام طويل الأمد قد يسهم في نقص الحديد.",
  },
  {
    id: 69,
    drug1: "Loperamide",
    drug1Ar: "لوبيراميد",
    drug2: "Ritonavir",
    drug2Ar: "ريتونافير",
    severity: "medium",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "Ritonavir inhibits P-glycoprotein, increasing loperamide CNS penetration and risk of cardiac arrhythmias at high doses.",
    descriptionAr: "ريتونافير يثبط البروتين السكري-P مما يزيد نفاذ لوبيراميد للجهاز العصبي المركزي وخطر اضطرابات نظم القلب بالجرعات العالية.",
  },
  {
    id: 70,
    drug1: "Misoprostol",
    drug1Ar: "ميزوبروستول",
    drug2: "Oxytocin",
    drug2Ar: "أوكسيتوسين",
    severity: "high",
    category: "stomach",
    categoryAr: "المعدة والجهاز الهضمي",
    descriptionEn: "Both stimulate uterine contractions. Combined use can cause uterine hyperstimulation, uterine rupture, and fetal distress.",
    descriptionAr: "كلاهما يحفز انقباضات الرحم. الجمع بينهما قد يسبب فرط تحفيز الرحم وتمزقه وضائقة جنينية.",
  },

  // ===== VITAMINS & SUPPLEMENTS (71-80) =====
  {
    id: 71,
    drug1: "Calcium Supplements",
    drug1Ar: "مكملات الكالسيوم",
    drug2: "Levothyroxine",
    drug2Ar: "ليفوثيروكسين",
    severity: "medium",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Calcium binds levothyroxine in the gut, reducing its absorption. Separate doses by at least 4 hours.",
    descriptionAr: "الكالسيوم يرتبط بالليفوثيروكسين في الأمعاء مما يقلل امتصاصه. يجب الفصل بـ4 ساعات على الأقل.",
  },
  {
    id: 72,
    drug1: "Iron Supplements",
    drug1Ar: "مكملات الحديد",
    drug2: "Levothyroxine",
    drug2Ar: "ليفوثيروكسين",
    severity: "medium",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Iron forms an insoluble complex with levothyroxine, significantly reducing thyroid hormone absorption. Separate by 4 hours.",
    descriptionAr: "الحديد يكوّن مركباً غير قابل للذوبان مع ليفوثيروكسين مما يقلل امتصاص هرمون الغدة الدرقية بشكل كبير. يجب الفصل بـ4 ساعات.",
  },
  {
    id: 73,
    drug1: "St. John's Wort",
    drug1Ar: "نبتة سانت جون",
    drug2: "Sertraline",
    drug2Ar: "سيرترالين",
    severity: "high",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Both increase serotonin. Combined use can cause serotonin syndrome. St. John's Wort also induces drug-metabolizing enzymes.",
    descriptionAr: "كلاهما يزيد السيروتونين. الجمع بينهما قد يسبب متلازمة السيروتونين. نبتة سانت جون تحفز أيضاً إنزيمات أيض الأدوية.",
  },
  {
    id: 74,
    drug1: "Potassium Supplements",
    drug1Ar: "مكملات البوتاسيوم",
    drug2: "Lisinopril",
    drug2Ar: "ليسينوبريل",
    severity: "high",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "ACE inhibitors reduce potassium excretion. Adding potassium supplements significantly increases the risk of fatal hyperkalemia.",
    descriptionAr: "مثبطات ACE تقلل إخراج البوتاسيوم. إضافة مكملات البوتاسيوم يزيد بشكل كبير خطر ارتفاع البوتاسيوم المميت.",
  },
  {
    id: 75,
    drug1: "Vitamin K",
    drug1Ar: "فيتامين ك",
    drug2: "Warfarin",
    drug2Ar: "وارفارين",
    severity: "high",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Vitamin K directly antagonizes warfarin's anticoagulant mechanism. Variable vitamin K intake causes unstable INR control.",
    descriptionAr: "فيتامين ك يعاكس مباشرة آلية عمل وارفارين المضادة للتخثر. تناول متفاوت لفيتامين ك يسبب عدم استقرار التحكم في INR.",
  },
  {
    id: 76,
    drug1: "Magnesium Supplements",
    drug1Ar: "مكملات الماغنسيوم",
    drug2: "Ciprofloxacin",
    drug2Ar: "سيبروفلوكساسين",
    severity: "medium",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Magnesium chelates ciprofloxacin in the GI tract, substantially reducing antibiotic absorption and effectiveness.",
    descriptionAr: "الماغنسيوم يرتبط بالسيبروفلوكساسين في الجهاز الهضمي مما يقلل بشكل كبير امتصاص وفعالية المضاد الحيوي.",
  },
  {
    id: 77,
    drug1: "Fish Oil (Omega-3)",
    drug1Ar: "زيت السمك (أوميجا-3)",
    drug2: "Warfarin",
    drug2Ar: "وارفارين",
    severity: "low",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "High-dose fish oil may have mild antiplatelet effects, slightly increasing bleeding risk with warfarin. Monitor INR.",
    descriptionAr: "زيت السمك بجرعات عالية قد يكون له تأثير خفيف مضاد للصفائح مما يزيد خطر النزيف قليلاً مع وارفارين. يجب متابعة INR.",
  },
  {
    id: 78,
    drug1: "Zinc Supplements",
    drug1Ar: "مكملات الزنك",
    drug2: "Tetracycline",
    drug2Ar: "تتراسيكلين",
    severity: "medium",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Zinc chelates tetracycline in the GI tract, reducing absorption of both. Separate doses by at least 2 hours.",
    descriptionAr: "الزنك يرتبط بالتتراسيكلين في الجهاز الهضمي مما يقلل امتصاص كليهما. يجب الفصل بساعتين على الأقل.",
  },
  {
    id: 79,
    drug1: "Vitamin D",
    drug1Ar: "فيتامين د",
    drug2: "Thiazide Diuretics",
    drug2Ar: "مدرات الثيازيد",
    severity: "low",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Thiazides reduce calcium excretion. Combined with vitamin D (which increases calcium absorption), this may cause hypercalcemia.",
    descriptionAr: "الثيازيد يقلل إخراج الكالسيوم. مع فيتامين د (الذي يزيد امتصاص الكالسيوم) قد يسبب ارتفاع الكالسيوم في الدم.",
  },
  {
    id: 80,
    drug1: "Ginkgo Biloba",
    drug1Ar: "جنكو بيلوبا",
    drug2: "Aspirin",
    drug2Ar: "أسبرين",
    severity: "medium",
    category: "supplements",
    categoryAr: "الفيتامينات والمكملات",
    descriptionEn: "Ginkgo has antiplatelet properties. Combined with aspirin, it increases the risk of bleeding including intracranial hemorrhage.",
    descriptionAr: "الجنكو له خصائص مضادة للصفائح. مع الأسبرين يزيد خطر النزيف بما في ذلك النزيف داخل الجمجمة.",
  },

  // ===== HORMONES (81-90) =====
  {
    id: 81,
    drug1: "Levothyroxine",
    drug1Ar: "ليفوثيروكسين",
    drug2: "Warfarin",
    drug2Ar: "وارفارين",
    severity: "medium",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Thyroid hormones increase catabolism of vitamin K-dependent clotting factors, enhancing warfarin's anticoagulant effect.",
    descriptionAr: "هرمونات الغدة الدرقية تزيد تكسير عوامل التخثر المعتمدة على فيتامين ك مما يعزز تأثير وارفارين المضاد للتخثر.",
  },
  {
    id: 82,
    drug1: "Oral Contraceptives",
    drug1Ar: "حبوب منع الحمل",
    drug2: "Carbamazepine",
    drug2Ar: "كاربامازيبين",
    severity: "high",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Carbamazepine induces CYP3A4, increasing contraceptive hormone metabolism and causing contraceptive failure.",
    descriptionAr: "كاربامازيبين يحفز إنزيم CYP3A4 مما يزيد أيض هرمونات منع الحمل ويسبب فشل وسيلة منع الحمل.",
  },
  {
    id: 83,
    drug1: "Prednisolone",
    drug1Ar: "بريدنيزولون",
    drug2: "Ibuprofen",
    drug2Ar: "بروفين",
    severity: "medium",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Combined use greatly increases the risk of GI ulceration and bleeding. A proton pump inhibitor should be co-prescribed.",
    descriptionAr: "الجمع بينهما يزيد بشكل كبير خطر تقرح ونزيف الجهاز الهضمي. يجب وصف مثبط مضخة البروتون معهما.",
  },
  {
    id: 84,
    drug1: "Dexamethasone",
    drug1Ar: "ديكساميثازون",
    drug2: "Phenytoin",
    drug2Ar: "فينيتوين",
    severity: "medium",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Phenytoin induces CYP3A4, reducing dexamethasone efficacy. Dexamethasone dose may need to be doubled.",
    descriptionAr: "فينيتوين يحفز إنزيم CYP3A4 مما يقلل فعالية ديكساميثازون. قد يحتاج مضاعفة جرعة ديكساميثازون.",
  },
  {
    id: 85,
    drug1: "Estrogen (HRT)",
    drug1Ar: "إستروجين (هرمون تعويضي)",
    drug2: "Lamotrigine",
    drug2Ar: "لاموتريجين",
    severity: "medium",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Estrogen increases lamotrigine glucuronidation, reducing its levels by up to 50% and potentially causing seizure breakthrough.",
    descriptionAr: "الإستروجين يزيد تحلل لاموتريجين بالجلوكورونيد مما يقلل مستوياته حتى 50% وقد يسبب عودة النوبات التشنجية.",
  },
  {
    id: 86,
    drug1: "Testosterone",
    drug1Ar: "تستوستيرون",
    drug2: "Warfarin",
    drug2Ar: "وارفارين",
    severity: "medium",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Testosterone can enhance warfarin's anticoagulant effect, increasing INR and bleeding risk. Close monitoring is required.",
    descriptionAr: "التستوستيرون قد يعزز تأثير وارفارين المضاد للتخثر مما يزيد INR وخطر النزيف. يجب المتابعة الدقيقة.",
  },
  {
    id: 87,
    drug1: "Levothyroxine",
    drug1Ar: "ليفوثيروكسين",
    drug2: "Omeprazole",
    drug2Ar: "أوميبرازول",
    severity: "low",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "PPIs reduce gastric acid, which may decrease levothyroxine absorption. TSH should be monitored and dose adjusted if needed.",
    descriptionAr: "مثبطات مضخة البروتون تقلل حمض المعدة مما قد يقلل امتصاص ليفوثيروكسين. يجب متابعة TSH وتعديل الجرعة عند الحاجة.",
  },
  {
    id: 88,
    drug1: "Insulin",
    drug1Ar: "إنسولين",
    drug2: "Prednisolone",
    drug2Ar: "بريدنيزولون",
    severity: "medium",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Corticosteroids raise blood glucose by promoting gluconeogenesis and insulin resistance. Insulin dose usually needs to be increased.",
    descriptionAr: "الكورتيكوستيرويدات ترفع سكر الدم عبر تحفيز استحداث السكر ومقاومة الإنسولين. عادة يحتاج زيادة جرعة الإنسولين.",
  },
  {
    id: 89,
    drug1: "Oral Contraceptives",
    drug1Ar: "حبوب منع الحمل",
    drug2: "Phenytoin",
    drug2Ar: "فينيتوين",
    severity: "high",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Phenytoin induces hepatic enzymes that metabolize contraceptive hormones, leading to reduced efficacy and unplanned pregnancy.",
    descriptionAr: "فينيتوين يحفز الإنزيمات الكبدية التي تكسر هرمونات منع الحمل مما يقلل فعاليتها ويسبب حملاً غير مخطط له.",
  },
  {
    id: 90,
    drug1: "Hydrocortisone",
    drug1Ar: "هيدروكورتيزون",
    drug2: "Ketoconazole",
    drug2Ar: "كيتوكونازول",
    severity: "medium",
    category: "hormones",
    categoryAr: "الهرمونات",
    descriptionEn: "Ketoconazole inhibits cortisol synthesis and CYP3A4 metabolism of hydrocortisone, leading to unpredictable cortisol levels.",
    descriptionAr: "كيتوكونازول يثبط تصنيع الكورتيزول وأيض الهيدروكورتيزون عبر CYP3A4 مما يؤدي لمستويات كورتيزول غير متوقعة.",
  },

  // ===== OTHER (91-100) =====
  {
    id: 91,
    drug1: "Sildenafil",
    drug1Ar: "سيلدينافيل",
    drug2: "Nitroglycerin",
    drug2Ar: "نيتروجليسرين",
    severity: "high",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Both are vasodilators via the nitric oxide pathway. Combined use can cause life-threatening hypotension and cardiovascular collapse.",
    descriptionAr: "كلاهما موسع للأوعية عبر مسار أكسيد النيتريك. الجمع بينهما قد يسبب انخفاضاً مهدداً للحياة في الضغط وانهياراً قلبياً وعائياً.",
  },
  {
    id: 92,
    drug1: "Allopurinol",
    drug1Ar: "ألوبيورينول",
    drug2: "Azathioprine",
    drug2Ar: "أزاثيوبرين",
    severity: "high",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Allopurinol inhibits xanthine oxidase, blocking azathioprine metabolism and causing severe pancytopenia. Dose must be reduced 75%.",
    descriptionAr: "ألوبيورينول يثبط أوكسيداز الزانثين مما يمنع أيض أزاثيوبرين ويسبب نقصاً حاداً في خلايا الدم. يجب تقليل الجرعة 75%.",
  },
  {
    id: 93,
    drug1: "Theophylline",
    drug1Ar: "ثيوفيللين",
    drug2: "Cimetidine",
    drug2Ar: "سيميتيدين",
    severity: "medium",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Cimetidine inhibits hepatic CYP enzymes, increasing theophylline levels and risk of toxicity with nausea, seizures, and arrhythmias.",
    descriptionAr: "سيميتيدين يثبط إنزيمات CYP الكبدية مما يزيد مستوى ثيوفيللين وخطر التسمم مع غثيان وتشنجات واضطراب نظم القلب.",
  },
  {
    id: 94,
    drug1: "Cyclosporine",
    drug1Ar: "سيكلوسبورين",
    drug2: "Atorvastatin",
    drug2Ar: "أتورفاستاتين",
    severity: "high",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Cyclosporine markedly increases statin levels through CYP3A4 inhibition and transporter inhibition, greatly increasing rhabdomyolysis risk.",
    descriptionAr: "سيكلوسبورين يزيد بشكل ملحوظ مستويات الستاتين عبر تثبيط CYP3A4 والناقلات مما يزيد خطر انحلال العضلات بشكل كبير.",
  },
  {
    id: 95,
    drug1: "Salbutamol",
    drug1Ar: "سالبوتامول",
    drug2: "Propranolol",
    drug2Ar: "بروبرانولول",
    severity: "high",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Non-selective beta-blockers antagonize the bronchodilator effect of salbutamol and can trigger severe bronchospasm in asthma patients.",
    descriptionAr: "حاصرات بيتا غير الانتقائية تعاكس تأثير سالبوتامول الموسع للشعب وقد تسبب تشنجاً رئوياً حاداً في مرضى الربو.",
  },
  {
    id: 96,
    drug1: "Montelukast",
    drug1Ar: "مونتيلوكاست",
    drug2: "Phenobarbital",
    drug2Ar: "فينوباربيتال",
    severity: "medium",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Phenobarbital induces CYP3A4, increasing montelukast metabolism and potentially reducing its effectiveness for asthma control.",
    descriptionAr: "فينوباربيتال يحفز إنزيم CYP3A4 مما يزيد أيض مونتيلوكاست وقد يقلل فعاليته في السيطرة على الربو.",
  },
  {
    id: 97,
    drug1: "Tamsulosin",
    drug1Ar: "تامسولوسين",
    drug2: "Sildenafil",
    drug2Ar: "سيلدينافيل",
    severity: "medium",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Both lower blood pressure. Combined use increases the risk of orthostatic hypotension, dizziness, and syncope.",
    descriptionAr: "كلاهما يخفض ضغط الدم. الجمع بينهما يزيد خطر انخفاض الضغط الوضعي والدوخة والإغماء.",
  },
  {
    id: 98,
    drug1: "Chlorpheniramine",
    drug1Ar: "كلورفينيرامين",
    drug2: "Amitriptyline",
    drug2Ar: "أميتريبتيلين",
    severity: "medium",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Both have anticholinergic effects. Combined use increases the risk of dry mouth, urinary retention, constipation, and confusion in elderly.",
    descriptionAr: "كلاهما له تأثيرات مضادة للكولين. الجمع بينهما يزيد خطر جفاف الفم واحتباس البول والإمساك والارتباك في المسنين.",
  },
  {
    id: 99,
    drug1: "Finasteride",
    drug1Ar: "فيناستيرايد",
    drug2: "Saw Palmetto",
    drug2Ar: "بلميط منشاري",
    severity: "low",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Both have anti-androgenic effects. Combined use may lead to additive hormonal suppression. Clinical significance is uncertain.",
    descriptionAr: "كلاهما له تأثيرات مضادة للأندروجين. الجمع بينهما قد يؤدي لتثبيط هرموني إضافي. الأهمية السريرية غير مؤكدة.",
  },
  {
    id: 100,
    drug1: "Diphenhydramine",
    drug1Ar: "ديفينهيدرامين",
    drug2: "Alcohol",
    drug2Ar: "كحول",
    severity: "high",
    category: "other",
    categoryAr: "أخرى",
    descriptionEn: "Both are CNS depressants. Combined use causes excessive sedation, impaired motor function, and risk of respiratory depression.",
    descriptionAr: "كلاهما مثبط للجهاز العصبي المركزي. الجمع بينهما يسبب تخديراً مفرطاً وضعف الوظائف الحركية وخطر التثبيط التنفسي.",
  },
];

export function searchInteractions(query: string): DrugInteraction[] {
  const q = query.toLowerCase().trim();
  if (!q) return drugInteractions;
  return drugInteractions.filter(i =>
    i.drug1.toLowerCase().includes(q) || i.drug1Ar.includes(query.trim()) ||
    i.drug2.toLowerCase().includes(q) || i.drug2Ar.includes(query.trim()) ||
    i.descriptionEn.toLowerCase().includes(q) || i.descriptionAr.includes(query.trim())
  );
}
